public class sample {
    public static void operations(Integer X1 ,Integer X2 ,String S1,String S2 )
    {
        system.debug('Mathmatical Operations');
        system.debug('x1=21');
        system.debug('x2=34');
        system.debug('x1+x2 = '+(x1+x2));
        system.debug('x1*x2 = '+(x1*x2));
        system.debug('x1-x2 = '+(x1-x2));
        system.debug('x1/x2 = '+(x1/x2));
        system.debug('String Operations');
        system.debug('concatination of '+S1+' and '+S2+ ' is '+S1+S2);
        system.debug('Equal op of '+S1+' and '+S2+ ' is '+(S1==S2));
    }
}